---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: backstage-db
spec:
  instances: 3
  bootstrap:
    initdb:
      database: backstage
      owner: backstage
      secret:
        name: backstage-db-creds
      postInitApplicationSQL:
        - |
          ALTER USER backstage CREATEDB;
  storage:
    size: 1Gi
  # enableSuperuserAccess: true