---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: nextcloud-db
spec:
  instances: 1
  bootstrap:
    # initdb:
    #   database: nextcloud
    #   owner: nextcloud
    #   postInitApplicationSQL:
    #     - |
    #       ALTER USER nextcloud CREATEDB;
    recovery:
      database: nextcloud
      owner: nextcloud
      postInitApplicationSQL:
        - |
          ALTER USER nextcloud CREATEDB;
      volumeSnapshots:
        storage:
          name: nextcloud-snapshot-db-backup
          kind: VolumeSnapshot
          apiGroup: snapshot.storage.k8s.io
        walStorage:
          name: nextcloud-snapshot-db-backup-wal
          kind: VolumeSnapshot
          apiGroup: snapshot.storage.k8s.io
  storage:
    storageClass: longhorn
    size: 10Gi
  walStorage:
    storageClass: longhorn
    size: 10Gi
  backup:
    volumeSnapshot:
      className: longhorn-backup-vsc
  # enableSuperuserAccess: true

