---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nextcloud
resources:
  - ../../base/nextcloud/
patches:
  - path: ingress.yaml
    target:
      kind: Ingress
      name: nextcloud-ingress