---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotContent
metadata:
  name: nextcloud-data-backup
spec:
  volumeSnapshotClassName: longhorn-backup-vsc
  driver: driver.longhorn.io
  deletionPolicy: Delete
  source:
    snapshotHandle: bak://pvc-4be27d0d-6aba-47f7-b52a-c2f704429b5a/backup-8930b027d4064f2f
  volumeSnapshotRef:
    name: nextcloud-snapshot-data-backup
    namespace: nextcloud
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: nextcloud-snapshot-data-backup
spec:
  volumeSnapshotClassName: longhorn-backup-vsc
  source:
    volumeSnapshotContentName: nextcloud-data-backup
