---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotContent
metadata:
  name: nextcloud-pvc-data-content
  namespace: longhorn-system
spec:
  volumeSnapshotClassName: longhorn-backup-vsc
  driver: driver.longhorn.io
  deletionPolicy: Delete
  source:
    snapshotHandle: bak://pvc-1a7a7edd-82c8-40d9-8293-af28ee715c0c/backup-92e056bca0ff460c
  volumeSnapshotRef:
    name: nextcloud-pvc-data-snapshot
    namespace: nextcloud
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: nextcloud-pvc-data-snapshot
  namespace: nextcloud
spec:
  volumeSnapshotClassName: longhorn-backup-vsc
  source:
    volumeSnapshotContentName: nextcloud-pvc-data-content

---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotContent
metadata:
  name: nextcloud-database-content
  namespace: longhorn-system
spec:
  volumeSnapshotClassName: longhorn-backup-vsc
  driver: driver.longhorn.io
  deletionPolicy: Delete
  source:
    snapshotHandle: bak://pvc-616eca9d-85f3-4a2b-bacf-0776eb5e207c/backup-e5fb578c57364fe5
  volumeSnapshotRef:
    name: nextcloud-database-snapshot
    namespace: nextcloud
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: nextcloud-database-snapshot
  namespace: nextcloud
spec:
  volumeSnapshotClassName: longhorn-backup-vsc
  source:
    volumeSnapshotContentName: nextcloud-database-content

---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotContent
metadata:
  name: nextcloud-database-wal-content
  namespace: longhorn-system
spec:
  volumeSnapshotClassName: longhorn-backup-vsc
  driver: driver.longhorn.io
  deletionPolicy: Delete
  source:
    snapshotHandle: bak://pvc-19c330bb-c360-4204-bb58-3169f73fd9c1/backup-23539b6996a841c1
  volumeSnapshotRef:
    name: nextcloud-database-wal-snapshot
    namespace: nextcloud
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: nextcloud-database-wal-snapshot
  namespace: nextcloud
spec:
  volumeSnapshotClassName: longhorn-backup-vsc
  source:
    volumeSnapshotContentName: nextcloud-database-wal-content
