---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotContent
metadata:
  name: nextcloud-db-backup
spec:
  volumeSnapshotClassName: longhorn-backup-vsc
  driver: driver.longhorn.io
  deletionPolicy: Delete
  source:
    snapshotHandle: bak://pvc-b68ec363-ac39-4fe0-9856-026287181332/backup-89e46692d8394669
  volumeSnapshotRef:
    name: nextcloud-snapshot-db-backup
    namespace: nextcloud
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: nextcloud-snapshot-db-backup
spec:
  volumeSnapshotClassName: longhorn-backup-vsc
  source:
    volumeSnapshotContentName: nextcloud-db-backup
