---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nfs-subdir-external-provisioner
spec:
  chart:
    spec:
      version: "*"
  values:
    nfs:
      server: "10.42.2.87"
      path: "/volume1/ts-k8s-data"
