---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: users-db-api
  namespace: flux-system
spec:
  interval: 1h0m0s
  path: ./manifest
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: users-db-api
  targetNamespace: users-db-api
  timeout: 3m0s
  wait: true
