---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: users-db-api
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: master
  url: ssh://git@github.com/micha-aucoin/users-db-api
  secretRef:
    name: users-db-api
