---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nfs-provisioner
resources:
  - service.yaml
  - ../../base/nfs-subdir-external-provisioner
patches:
  - path: release.yaml
    target:
      kind: HelmRelease
