---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nfs-subdir-external-provisioner
spec:
  chart:
    spec:
      version: "*"
  values:
    nfs:
      server: "ts-nas-service-kn7bv.tailscale.svc.cluster.local"
      path: "/volume1/ts-k8s-data"
