---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared
data:
  config.yaml: |
    tunnel: nextcloud
    ingress:
    - hostname: nextcloud.boxadvisers.com
      service: http://nextcloud-http.nextcloud:80
