---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared
data:
  config.yaml: |
    tunnel: nextcloud
    credentials-file: /etc/cloudflared/creds/nextcloud
    metrics: 0.0.0.0:2000
    no-autoupdate: true
    ingress:
    - hostname: nextcloud.boxadvisers.com
      service: http://nextcloud-https.nextcloud:80
            ## http://<svc>.<namespace>:<port> ##
    - service: http_status:404
