apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nextcloud
resources:
  - ../../base/nextcloud/
patches:
  - path: configmap.yaml
    target:
      kind: ConfigMap
  - path: deployment.yaml
    target:
      kind: Deployment
