---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  # - volumes.yaml
  # - snapshots.yaml
  - database-storage.yaml
  - ../../base/nextcloud
  # - ../../base/cloudflare/
  - ingress.yaml
# patches:
  # - patch: |-
  #     apiVersion: v1
  #     kind: ConfigMap
  #     metadata:
  #       name: cloudflared
  #     data:
  #       config.yaml: |
  #         tunnel: nextcloud
  #         credentials-file: /etc/cloudflared/creds/credentials.json
  #         metrics: 0.0.0.0:2000
  #         no-autoupdate: true
  #         ingress:
  #         - hostname: nextcloud.boxadvisers.com
  #           service: http://nextcloud-http.nextcloud:80
  #         - hostname: hello.example.com
  #           service: hello_world
  #         - service: http_status:404
  # - patch: |-
  #     apiVersion: apps/v1
  #     kind: Deployment
  #     metadata:
  #       name: cloudflared
  #     spec:
  #       replicas: 1
  #       template:
  #         spec:
  #           nodeSelector:
  #             node-type: amd64
