---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nextcloud
resources:
  - ../../base/nextcloud/
#   - ../../base/cloudflare/
# patches:
#   - path: configmap.yaml
#     target:
#       kind: ConfigMap
#       name: cloudflared
#   - path: deployment.yaml
#     target:
#       kind: Deployment
#       name: cloudflared
