---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotContent
metadata:
  name: nextcloud-pvc-data-content
  namespace: longhorn-system
spec:
  volumeSnapshotClassName: longhorn-backup-vsc
  driver: driver.longhorn.io
  deletionPolicy: Delete
  source:
    snapshotHandle: bak://pvc-4be27d0d-6aba-47f7-b52a-c2f704429b5a/backup-8930b027d4064f2f
  volumeSnapshotRef:
    name: nextcloud-pvc-data-snapshot
    namespace: nextcloud
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: nextcloud-pvc-data-snapshot
  namespace: longhorn-system
spec:
  volumeSnapshotClassName: longhorn-backup-vsc
  source:
    volumeSnapshotContentName: nextcloud-pvc-data-content

---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotContent
metadata:
  name: nextcloud-database-content
  namespace: longhorn-system
spec:
  volumeSnapshotClassName: longhorn-backup-vsc
  driver: driver.longhorn.io
  deletionPolicy: Delete
  source:
    snapshotHandle: bak://pvc-b68ec363-ac39-4fe0-9856-026287181332/backup-715d6fd2f3d34735
  volumeSnapshotRef:
    name: nextcloud-database-snapshot
    namespace: nextcloud
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: nextcloud-database-snapshot
  namespace: longhorn-system
spec:
  volumeSnapshotClassName: longhorn-backup-vsc
  source:
    volumeSnapshotContentName: nextcloud-database-content

---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotContent
metadata:
  name: nextcloud-database-wal-content
  namespace: longhorn-system
spec:
  volumeSnapshotClassName: longhorn-backup-vsc
  driver: driver.longhorn.io
  deletionPolicy: Delete
  source:
    snapshotHandle: bak://pvc-01f2e510-3477-4910-baf4-dae7b755f652/backup-831015e2c4f74563
  volumeSnapshotRef:
    name: nextcloud-database-wal-snapshot
    namespace: nextcloud
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: nextcloud-database-wal-snapshot
  namespace: longhorn-system
spec:
  volumeSnapshotClassName: longhorn-backup-vsc
  source:
    volumeSnapshotContentName: nextcloud-database-wal-content
