---
apiVersion: longhorn.io/v1beta1
kind: Volume
metadata:
  name: nextcloud-pvc-data-volume
spec:
  size: 10Gi
  numberOfReplicas: 2
  frontend: blockdev
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-pvc-data-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  persistentVolumeReclaimPolicy: Delete
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeAttributes:
      numberOfReplicas: "2"
    volumeHandle: nextcloud-pvc-data-volume

---
apiVersion: longhorn.io/v1beta1
kind: Volume
metadata:
  name: nextcloud-database-volume
spec:
  size: 10Gi
  numberOfReplicas: 2
  frontend: blockdev
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-database-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  persistentVolumeReclaimPolicy: Delete
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeAttributes:
      numberOfReplicas: "2"
    volumeHandle: nextcloud-database-volume

---
apiVersion: longhorn.io/v1beta1
kind: Volume
metadata:
  name: nextcloud-database-wal-volume
spec:
  size: 10Gi
  numberOfReplicas: 2
  frontend: blockdev
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-database-wal-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  persistentVolumeReclaimPolicy: Delete
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeAttributes:
      numberOfReplicas: "2"
    volumeHandle: nextcloud-database-wal-volume
