---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotContent
metadata:
  name: pgadmin-data-backup
spec:
  volumeSnapshotClassName: longhorn-backup-vsc
  driver: driver.longhorn.io
  deletionPolicy: Delete
  source:
    snapshotHandle: bak://NA/NA
  volumeSnapshotRef:
    name: pgadmin-snapshot-data-backup
    namespace: pgadmin
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: pgadmin-snapshot-data-backup
spec:
  volumeSnapshotClassName: longhorn-backup-vsc
  source:
    volumeSnapshotContentName: pgadmin-data-backup
