apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ww-gitops-weave-gitops
spec:
  defaultBackend:
    service:
      name: ww-gitops-weave-gitops
      port:
        number: 9001
  ingressClassName: tailscale
  tls:
    - hosts:
        - ww-gitops-weave-gitops

