---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pgadmin-ingress
spec:
  ingressClassName: traefik
  rules:
  - host: pgadmin-s.boxadvisers.com
    http:
      paths:
      - backend:
          service:
            name: pgadmin-service
            port:
              number: 15432
        path: /
        pathType: Prefix
