---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotContent
metadata:
  name: pgadmin-pvc-data-content
  namespace: longhorn-system
spec:
  volumeSnapshotClassName: longhorn-backup-vsc
  driver: driver.longhorn.io
  deletionPolicy: Delete
  volumeSnapshotRef:
    name: pgadmin-pvc-data-snapshot
    namespace: pgadmin
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: pgadmin-pvc-data-snapshot
  namespace: longhorn-system
spec:
  volumeSnapshotClassName: longhorn-backup-vsc
  source:
    volumeSnapshotContentName: pgadmin-pvc-data-content
