# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: pgadmin-pvc-data
# spec:
#   storageClassName: longhorn
#   dataSource:
#     name: pgadmin-snapshot-data-backup
#     kind: VolumeSnapshot
#     apiGroup: snapshot.storage.k8s.io
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 500Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgadmin-pvc-data
  namespace: pgadmin
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
