---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: headplane-ingress
spec:
  ingressClassName: traefik
  rules:
    - host: headplane-s.boxadvisers.com
      http:
        paths:
        - backend:
            service:
              name: headplane-service
              port:
                number: 3000
          path: /admin
          pathType: Prefix
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: headscale-ingress
spec:
  ingressClassName: traefik
  rules:
    - host: headscale-s.boxadvisers.com
      http:
        paths:
        - backend:
            service:
              name: headscale-service
              port:
                number: 8080
          path: /
          pathType: Prefix
