---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - rbac.yaml
  - configmap.yaml
  - storage.yaml
  - deployment.yaml
  - service.yaml
  - network.yaml
  - ingress.yaml
