---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: csi-driver-nfs
resources:
  - ../../base/csi-driver-nfs
  - service.yaml
  - storageclass.yaml
  - local-path.yaml
patches:
  - path: nfs-client.yaml
    target:
      kind: StorageClass
      name: nfs-csi
