apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-csi
provisioner: nfs.csi.k8s.io
parameters:
  server: nas-service.nfs-provisioner.svc.cluster.local
  share: /volume1/ts-k8s-data
reclaimPolicy: Retain
volumeBindingMode: Immediate
