---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: nextcloud-db
spec:
  instances: 1
  bootstrap:
    initdb:
      database: nextcloud
      owner: nextcloud
      postInitApplicationSQL:
        - |
          ALTER USER nextcloud CREATEDB;
  storage:
    storageClass: longhorn
    size: 10Gi
  # enableSuperuserAccess: true
