apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - database.yaml
  - deployment.yaml
  - storage.yaml
  - service.yaml
  - https://raw.githubusercontent.com/cloudflare/argo-tunnel-examples/refs/heads/master/named-tunnel-k8s/cloudflared.yaml
