apiVersion: v1
kind: Service
metadata:
  name: nextcloud-http
spec:
  selector:
    app: nextcloud
  ports:
    - name: http
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nextcloud-https
spec:
  selector:
    app: nextcloud
  ports:
    - name: https
      port: 443
      targetPort: 443
