---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: pgadmin
  name: pgadmin-service
  namespace: pgadmin
spec:
  ports:
  - port: 15432
    protocol: TCP
    targetPort: 80
  selector:
    app: pgadmin
