---
apiVersion: v1
kind: Namespace
metadata:
  name: nfs-provisioner
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: nfs-subdir-external-provisioner
  namespace: nfs-provisioner
spec:
  interval: 1h0m0s
  url: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nfs-subdir-external-provisioner
  namespace: nfs-provisioner
spec:
  chart:
    spec:
      chart: nfs-subdir-external-provisioner
      sourceRef:
        kind: HelmRepository
        name: nfs-subdir-external-provisioner
      version: "*"
  install:
    createNamespace: true
  interval: 1h0m0s
  releaseName: nfs-subdir-external-provisioner
  valuesFrom:
    - kind: Secret
      name: nfs-values
      valuesKey: server
      targetPath: nfs.server
    - kind: Secret
      name: nfs-values
      valuesKey: path
      targetPath: nfs.path
