---
apiVersion: v1
kind: Namespace
metadata:
  name: tailscale
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: tailscale
  namespace: tailscale
spec:
  interval: 1h0m0s
  url: https://pkgs.tailscale.com/helmcharts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale-operator
  namespace: tailscale
spec:
  chart:
    spec:
      chart: tailscale-operator
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: tailscale
      version: '*'
  interval: 1h0m0s
  releaseName: tailscale-operator
  targetNamespace: tailscale
  install:
    createNamespace: true
  values:
    apiServerProxyConfig:
      mode: "true"
  valuesFrom:
    - kind: Secret
      name: oauth-client
      valuesKey: id
      targetPath: oauth.clientId
    - kind: Secret
      name: oauth-client
      valuesKey: secret
      targetPath: oauth.clientSecret